BOUNDS_WIDTH: int = 600
MAX_X: float = BOUNDS_WIDTH /2
MIN_X: float = -MAX_X
VIEW_WIDTH: int = BOUNDS_WIDTH + 20

BOUNDS_HEIGHT: int = 400
MAX_Y: float = BOUNDS_HEIGHT / 2
MIN_Y: float = -MAX_Y
VIEW_HEIGHT: int = BOUNDS_HEIGHT + 20

CELL_RADIUS: int = 15
CELL_COUNT: int = 1
CELL_SPEED: float = 5.0


GENOME_SIZE = 100
BATTERIES_COUNT = 4
ROBOTS_COUNT = 500
NEXT_GEN_COUNT = 10
ROBOT_RADIUS = 10
BATTERY_RADIUS = 20
BATTERY_PICKUP_RADIUS = 30

DIRECTION_CHANGE_TICKS = 10
ACCELERATION_CONSTANT = 1
SPEED_CONSTANT = 1
INITIAL_SPEED = 0

TURTLE_SPEED_INDICATOR_CONSTANT = 10
TURTLE_ACCELERATION_INDICATOR_CONSTANT = 20

WALL_COUNT = 0
WALL_SIZE = 200
TICKS_PER_SCREEN_UPDATE = 6
GENERATION_PRINT_RATE = 10
FITNESS_CONSTANT = 1

MUTATION_CONSTANT = 10
FLIP_CONSTANT = 5

GENERATIONS_MAX = 100000
