BOUNDS_WIDTH: int = 600
MAX_X: float = BOUNDS_WIDTH /2
MIN_X: float = -MAX_X
VIEW_WIDTH: int = BOUNDS_WIDTH + 20

BOUNDS_HEIGHT: int = 400
MAX_Y: float = BOUNDS_HEIGHT / 2
MIN_Y: float = -MAX_Y
VIEW_HEIGHT: int = BOUNDS_HEIGHT + 20

CELL_RADIUS: int = 15
CELL_COUNT: int = 1
CELL_SPEED: float = 5.0


GENOME_SIZE = 100
BATTERIES_COUNT = 1
ROBOTS_COUNT = 100
NEXT_GEN_COUNT = 30
ROBOT_RADIUS = 10
BATTERY_RADIUS = 20
BATTERY_PICKUP_RADIUS = 20

DIRECTION_CHANGE_TICKS = 8
ACCELERATION_CONSTANT = 1
SPEED_CONSTANT = 0.01
INITIAL_SPEED = 0

TURTLE_SPEED_INDICATOR_CONSTANT = 1
TURTLE_ACCELERATION_INDICATOR_CONSTANT = 20

WALL_COUNT = 0
WALL_SIZE = 200
FITNESS_CONSTANT = 1

MUTATION_CONSTANT = 3
FLIP_CONSTANT = 2

GENERATIONS_MAX = 100000

GENERATION_PRINT_RATE = 10
TICKS_PER_SCREEN_UPDATE = 6
KEEP_SPEED_CONSTANT = 1