
ROBOT_COLOR = "green"
DEAD_ROBOT_COLOR = "red"
ROBOT_SPEED_COLOR = "yellow"
# board size 
BOUNDS_WIDTH: int = 1000
MAX_X: float = BOUNDS_WIDTH /2
MIN_X: float = -MAX_X
VIEW_WIDTH: int = BOUNDS_WIDTH + 20
BOUNDS_HEIGHT: int = 600
MAX_Y: float = BOUNDS_HEIGHT / 2
MIN_Y: float = -MAX_Y
VIEW_HEIGHT: int = BOUNDS_HEIGHT + 20


TURTLE_SPEED_INDICATOR_CONSTANT = 10
TURTLE_ACCELERATION_INDICATOR_CONSTANT = 10


ROBOTS_COUNT = 50
PRINT_ROBOTS_MAX = 10
ROBOT_RADIUS = 15
BATTERY_RADIUS = 20

SPEED_CONSTANT = 1

MUTATION_PROBABILITY = 0.000

GENERATIONS_MAX = 300000

GENERATION_PRINT_RATE = 1
TICKS_PER_SCREEN_UPDATE = 1

PRINT_BEST_ONLY = False
KEEP_BEST = False

PRINT_FIRST_N_GENERATIONS = 0
PRINT_DEAD_ROBOTS = True


MAX_TICKS = 2000
# ROBOT_RAY_ANGLES = [0, 0.06, -0.06, 0.12, -0.12]
ROBOT_RAY_ANGLES = [(0, 180), (0.075, 60), (-0.075, 60), (0.15, 30), (-0.15, 30) ]
ROBOT_FIXED_ANGLES = [0, 0.06, -0.06]
ROBOT_FIXED_DISTANCES = [35, 80]
SPEED_MIN = 1.5
SPEED_MAX = 2.5
SPEED_INCREMENT = 1
RAY_DISTANCE_INCEMENT = 20
RAY_MAX_DISTANCE = 120

ONE_ROTATION_ANGLE = 0.06

WALL = 0
BATTERY = 1
NOTHING = 2

LEFT = 0
RIGHT = 1
UP = 2
DOWN = 3
DIRECTIONS = [LEFT, RIGHT, UP, DOWN]

SAVE_ROBOTS = True
LOAD_ROBOTS = True









